// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYvnKIx8xbHaIkeg7h4EkE7W53pdkFaWk',
    appId: '1:781388358777:web:7f01552e153089bd0e20a8',
    messagingSenderId: '781388358777',
    projectId: 'db-rutaya-14ee3',
    authDomain: 'db-rutaya-14ee3.firebaseapp.com',
    databaseURL: 'https://db-rutaya-14ee3-default-rtdb.firebaseio.com',
    storageBucket: 'db-rutaya-14ee3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn_byr90Q3-CMI-wLGF957VoYUJf9uWvQ',
    appId: '1:781388358777:android:be7b730333dec1a70e20a8',
    messagingSenderId: '781388358777',
    projectId: 'db-rutaya-14ee3',
    databaseURL: 'https://db-rutaya-14ee3-default-rtdb.firebaseio.com',
    storageBucket: 'db-rutaya-14ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TLpki92KTXaE3450_v0cGtD8Irhem9g',
    appId: '1:781388358777:ios:080f513d861ea89e0e20a8',
    messagingSenderId: '781388358777',
    projectId: 'db-rutaya-14ee3',
    databaseURL: 'https://db-rutaya-14ee3-default-rtdb.firebaseio.com',
    storageBucket: 'db-rutaya-14ee3.firebasestorage.app',
    iosBundleId: 'com.example.rutayach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7TLpki92KTXaE3450_v0cGtD8Irhem9g',
    appId: '1:781388358777:ios:080f513d861ea89e0e20a8',
    messagingSenderId: '781388358777',
    projectId: 'db-rutaya-14ee3',
    databaseURL: 'https://db-rutaya-14ee3-default-rtdb.firebaseio.com',
    storageBucket: 'db-rutaya-14ee3.firebasestorage.app',
    iosBundleId: 'com.example.rutayach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYvnKIx8xbHaIkeg7h4EkE7W53pdkFaWk',
    appId: '1:781388358777:web:6387b9306d97770f0e20a8',
    messagingSenderId: '781388358777',
    projectId: 'db-rutaya-14ee3',
    authDomain: 'db-rutaya-14ee3.firebaseapp.com',
    databaseURL: 'https://db-rutaya-14ee3-default-rtdb.firebaseio.com',
    storageBucket: 'db-rutaya-14ee3.firebasestorage.app',
  );

}